#pragma once
#ifndef PRINTF_CONFIG_H_
#define PRINTF_CONFIG_H_

#define PRINTF_SUPPORT_DECIMAL_SPECIFIERS 0
#define PRINTF_SUPPORT_EXPONENTIAL_SPECIFIERS 0
#define PRINTF_SUPPORT_FLOAT_SPECIFIERS 0
#define PRINTF_SUPPORT_LONG_LONG 0

#endif // PRINTF_CONFIG_H_
